import React, { useState, useEffect } from 'react';
import api from '../api';
import { generateBookPDF } from '../utils/pdfGenerator';
import { Book, Download } from 'lucide-react';

const CompiledBooks = () => {
  const [books, setBooks] = useState([]);
  const [loadingIds, setLoadingIds] = useState({});

  const fetchBooks = async () => {
    try {
      const res = await api.get('/topics');
      // Filter strictly for topics that have been compiled
      const compiled = res.data.filter(t => t.isCompiled);
      setBooks(compiled);
    } catch (err) {
      console.error(err);
    }
  };

  useEffect(() => {
    fetchBooks();
  }, []);

  const handleDownload = async (topic) => {
    setLoadingIds(prev => ({ ...prev, [topic._id]: true }));
    try {
      const res = await api.get(`/submissions/topic/${topic._id}`);
      generateBookPDF(topic, res.data);
    } catch (err) {
      console.error(err);
      alert('Failed to download book. Please try again.');
    } finally {
      setLoadingIds(prev => ({ ...prev, [topic._id]: false }));
    }
  };

  // Function to generate deterministic gradients based on topic title
  const getGradient = (str) => {
    let hash = 0;
    for (let i = 0; i < str.length; i++) {
        hash = str.charCodeAt(i) + ((hash << 5) - hash);
    }
    const c1 = `hsl(${Math.abs(hash) % 360}, 70%, 20%)`;
    const c2 = `hsl(${(Math.abs(hash) + 60) % 360}, 70%, 15%)`;
    return `linear-gradient(135deg, ${c1}, ${c2})`;
  };

  return (
    <div className="container" style={{ marginTop: '2rem' }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', marginBottom: '2rem' }}>
        <Book size={32} className="text-accent" />
        <h2 style={{ margin: 0 }}>Compiled Books Library</h2>
      </div>
      <p className="text-secondary mb-4">A digital collection of all completed volumes generated by the community.</p>

      {books.length === 0 && (
        <div className="card" style={{ textAlign: 'center', padding: '4rem' }}>
          <p className="text-secondary mb-0">The library is currently empty. Compile books from the Admin Dashboard.</p>
        </div>
      )}

      <div style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fill, minmax(250px, 1fr))',
        gap: '2rem'
      }}>
        {books.map(topic => (
          <div key={topic._id} style={{
            background: 'var(--surface)',
            border: '1px solid var(--border)',
            borderRadius: '12px',
            overflow: 'hidden',
            display: 'flex',
            flexDirection: 'column',
            boxShadow: '0 10px 30px rgba(0,0,0,0.3)',
            transition: 'transform 0.3s ease, box-shadow 0.3s ease',
          }}>
            {/* Book Cover visually generated via CSS */}
            <div style={{
              height: '320px',
              padding: '2rem',
              display: 'flex',
              flexDirection: 'column',
              justifyContent: 'center',
              alignItems: 'center',
              textAlign: 'center',
              background: getGradient(topic.title),
              borderBottom: '4px solid rgba(0,0,0,0.5)',
              position: 'relative'
            }}>
              {/* Spine effect */}
              <div style={{
                position: 'absolute',
                left: 0, top: 0, bottom: 0,
                width: '12px',
                background: 'rgba(255,255,255,0.1)',
                boxShadow: 'inset -2px 0 5px rgba(0,0,0,0.3)'
              }}></div>
              
              <h3 style={{ 
                color: 'white', 
                fontSize: '1.4rem', 
                lineHeight: 1.3,
                textShadow: '0 2px 4px rgba(0,0,0,0.8)',
                marginBottom: '1rem' 
              }}>
                {topic.title}
              </h3>
              <div style={{
                width: '40px',
                height: '2px',
                background: 'var(--accent)',
                marginBottom: '1rem'
              }}></div>
              <p style={{
                color: 'rgba(255,255,255,0.7)',
                fontSize: '0.9rem',
                textTransform: 'uppercase',
                letterSpacing: '1px',
                margin: 0
              }}>
                Vol. 1
              </p>
            </div>
            
            <div style={{ padding: '1.5rem', display: 'flex', flexDirection: 'column', gap: '1rem', flex: 1 }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem' }}>
                <span className="text-secondary">{topic.currentWordCount.toLocaleString()} words</span>
                <span className="text-secondary">{topic.currentSubmissions} chapters</span>
              </div>
              <button 
                className="primary" 
                style={{ width: '100%', display: 'flex', justifyContent: 'center', alignItems: 'center', gap: '0.5rem', marginTop: 'auto' }}
                onClick={() => handleDownload(topic)}
                disabled={loadingIds[topic._id]}
              >
                <Download size={18} /> {loadingIds[topic._id] ? 'Generating PDF...' : 'Download PDF'}
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default CompiledBooks;
